### ISSUE TITLE
InventoryConstraintsCannotBeFulfilledException on minimal min_inventory 

### ISSUE THREAD

**Issue by londown** [cmdty/storage#31]
InventoryConstraintsCannotBeFulfilledException: Valuation calculation cannot be performed as storage inventory constraints cannot be fulfilled.
   at Cmdty.Storage.StorageHelper.CalculateInventorySpace[T](ICmdtyStorage`1 storage, Double startingInventory, T currentPeriod)
   at Cmdty.Storage.IntrinsicStorageValuation`1.Calculate(T currentPeriod, Double startingInventory, TimeSeries`2 forwardCurve, ICmdtyStorage`1 storage, Func`2 settleDateRule, Func`3 discountFactors, Func`2 gridCalcFactory, IInterpolatorFactory interpolatorFactory, Double numericalTolerance)
   at Cmdty.Storage.IntrinsicStorageValuation`1.Cmdty.Storage.IIntrinsicCalculate<T>.Calculate()

With following time-varying inventory, setting min_inventory to even 3% of max_inventory, 6 month after storage_start is failing the constraints.

Code:
max_inventory = 1.0     # MWh

injection_duration = 100.0    # days
withdrawal_duration = injection_duration / 2.0    # days

max_injection_rate = max_inventory / injection_duration    # MWh / day
max_withdrawal_rate = max_inventory / withdrawal_duration    # MWh / day

yearly_period_index = pd.PeriodIndex(freq='D', data = ['2023-04-01', '2023-10-01', '2024-04-01'])

storage_time_varying = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-04-01',
    injection_cost = 0.0,
    withdrawal_cost = 0.0,
    min_inventory = pd.Series([0.0, 0.03 * max_inventory, 0.0], yearly_period_index).resample('D').fillna('pad'),
    max_inventory = pd.Series([max_inventory, max_inventory, max_inventory], yearly_period_index).resample('D').fillna('pad'),
    max_injection_rate = max_injection_rate,    
    max_withdrawal_rate = max_withdrawal_rate
)

three_factor_results = three_factor_seasonal_value(
        cmdty_storage = storage_time_varying , 
        val_date = '2023-04-01',
        inventory = 0 * max_inventory,
        fwd_curve = fwd_curve,
        interest_rates = ir_curve,
        settlement_rule = settlement_rule,
        num_sims = 2000,
        seed = 12,
        spot_mean_reversion = 91.0,
        spot_vol = 1.3,
        long_term_vol =  0.50,
        seasonal_vol = 0.19,
        basis_funcs = '1 + x_st + x_sw + x_lt + s + x_st**2 + x_sw**2 + x_lt**2 + s**2 + s * x_st',
        discount_deltas = True
    )

**Comment by cmdty** [comment]
@londown I'll take a look at this later.

**Comment by cmdty** [comment]
@londown I think you are seeing this error because by [default a CmdtyStorage instance assumes that the storage must be empty (i.e. zero inventory) by the end period](http://localhost:8888/notebooks/creating_storage_instances.ipynb#Terminal-Storage-Value). In your setup the step down from going from 0.03 * max_inventory to 0.0 is too big to be able to achieve given the withdrawal rate. The exception does not occur if you assign to the terminal_storage_npv CmdtyStorage constructor argument, which sets up the constraint to allow the terminal inventory to be anywhere between the min and the max.

**Comment by londown** [comment]
Hmm. Assuming a max_injection rate of 100 days (=0.01 * max_inventory / day), and max_withdrawal rate being double that at 50 days (=0.02 * max_inventory / day), and assuming these rates are unrestricted by current inventory, we have plenty of time to ramp up and down, twice over a course of 1 year.

Assuming summer (store up time) is Apr-Sep, and consumption from Oct-Mar, it is quite common to specify a constraint that the storage must be 30-50% full by end-July, and 85-95% full by end Sept. 

I'm not able get intrinsic value with a constraint of storage being only 3% full in 3 months time, while it can theoretically be filled up in 3 days. 

Something is off here.

I'm not good with multi-language debugging else would have loved to get this working. I hope you take up a full python version in future

**Comment by cmdty** [comment]
Ramping up isn't the problem, it's the ramping down from the penultimate day of the storage to the final day.

If you assign the min inventory to a variable and then print it out the final points are:
2024-03-30    0.03
2024-03-31    0.03
2024-04-01    0.00

The maximum withdrawal rate is 0.02, which means it is impossible to empty the storage on 2024-03-31 from it's minimum inventory level of 0.03. To be able to empty it you would need at most 0.02 inventory at 2024-03-30, this isn't possible because the min inventory is 0.03

You should be able to specify the type of constraints which you give examples of, but you need to either:
1) Allow terminal inventory to be non-zero.
2) Ensure that there isn't such a sharp drop in minimum inventory near the end of the storage to allow the storage to be emptied.

Does this make sense?

**Comment by londown** [comment]
Is it possible to split the model call into two parts? To Setup the model, and to Run the model.
And add a function to get a dump of daily constraints in between the two calls.

**Comment by cmdty** [comment]
I don't understand what this would involve. What would the "setup" phase do?

This doesn't sound like something I would spend time on implementing.

**Comment by cmdty** [comment]
@londown, here is another thought on specifying constraints to the model that you mentioned such as _"must be 30-50% full by end-July, and 85-95% full by end Sept"_. In this example do the constraints specify what the inventory must be the day after the specific dates mentioned? E.g. is there a constraint on the inventory on 1-Aug and 1-Oct? I'm guessing maybe not for the first constraint, and probably not for the second one. If it is the case that % constraint are only for specific dates, then the constraints that you need to pass to the model should be 0-100% for 1-Aug and 1-Oct. This will accurately reflect the real constraints, and then model will optimise to meet these. 

In the contrived example you gave above this would look something like the following which just constrains the min inventory to 3% on 1-Oct:

yearly_period_index = pd.PeriodIndex(freq='D', data = ['2023-04-01', '2023-10-01', '2023-10-02', '2024-04-01'])

storage_time_varying = CmdtyStorage(
freq='D',
storage_start = '2023-04-01',
storage_end = '2024-04-01',
injection_cost = 0.0,
withdrawal_cost = 0.0,
min_inventory = pd.Series([0.0, 0.03 * max_inventory, 0.0, 0.0], yearly_period_index).resample('D').fillna('pad'),
max_inventory = pd.Series([max_inventory, max_inventory, max_inventory, max_inventory], yearly_period_index).resample('D').fillna('pad'),
max_injection_rate = max_injection_rate,
max_withdrawal_rate = max_withdrawal_rate
)

**Comment by londown** [comment]
Thanks. I'll think this through.
