### ISSUE TITLE
Problems specifying complicated ratchet constraints

### ISSUE THREAD

**Issue by PatternMatching** [cmdty/storage#6]
Hi!  I'm trying to test the model (in python) with the below constraints:

    InjectWithdrawByInventoryAndPeriod(date(2020, 8, 28),
                                       [
                                           InjectWithdrawByInventory(0.0, -8300, 7900),
                                           InjectWithdrawByInventory(0.1505 * 1e6, -10300, 7900),
                                           InjectWithdrawByInventory(0.237 * 1e6, -10300, 6700),
                                           InjectWithdrawByInventory(0.305 * 1e6, -12300, 6700),
                                           InjectWithdrawByInventory(0.428 * 1e6, -14300, 6700),
                                           InjectWithdrawByInventory(0.438 * 1e6, -14300, 5500),
                                           InjectWithdrawByInventory(0.77 * 1e6, -14300, 4000),
                                           InjectWithdrawByInventory(0.97 * 1e6, -14300, 2500),
                                           InjectWithdrawByInventory(1.0 * 1e6, -14300, 2500),
                                       ])

Yes, the facility I have to value has kind of ridiculous ratchet constraints.  That said, upon plugging these constraints into your test code, I got the following stacktrace:

    Traceback (most recent call last):
      File "value_bistineau.py", line 76, in <module>
        interest_rates=interest_rate_curve, num_inventory_grid_points=1000)
      File "C:\miniconda\envs\cmdty-storage\lib\site-packages\cmdty_storage\intrinsic.py", line 74, in intrinsic_value
        net_val_results = net_cs.IIntrinsicCalculate[time_period_type](intrinsic_calc).Calculate()
    System.IndexOutOfRangeException: Index was outside the bounds of the array.
       at Cmdty.TimeSeries.TimeSeries`2.get_Item(TIndex index)
       at Cmdty.Storage.CmdtyStorageBuilderExtensions.<>c__DisplayClass5_0`1.<AddInjectWithdrawRanges>g__GetMinInventory|1(T period)
       at Cmdty.Storage.CmdtyStorage`1.GetInjectWithdrawRange(T date, Double inventory)
       at Cmdty.Storage.StorageHelper.CalculateInventorySpace[T](ICmdtyStorage`1 storage, Double startingInventory, T currentPeriod)
       at Cmdty.Storage.IntrinsicStorageValuation`1.Calculate(T currentPeriod, Double startingInventory, TimeSeries`2 forwardCurve, ICmdtyStorage`1 storage, Func`2 settleDateRule, Func`3 discountFactors, Func`2 gridCalcFactory, IInterpolatorFactory interpolatorFactory, Double numericalTolerance)
       at Cmdty.Storage.IntrinsicStorageValuation`1.Cmdty.Storage.IIntrinsicCalculate<T>.Calculate()

Is it possible that I've misunderstood how to specify the constraints?

**Comment by cmdty** [comment]
Hi, can you post more code so that I can see all the parameters of the storage facility and the valuation model? Attaching a zipped Jupyter Notebook would be ideal.

**Comment by PatternMatching** [comment]
I don't have it setup as a Jupyter notebook at the moment, but this should be run-able in isolation using a python distro that has cmdty-storage installed.  Most of it is just ripped from the test valuation code snippet you have posted.

[value_bistineau.zip](https://github.com/cmdty/storage/files/4595897/value_bistineau.zip)

**Comment by cmdty** [comment]
I can see the problem. You storage_start is 2019-08-28, whereas your ratchets start for the same day but the year later, i.e. **2020**.
